### ISSUE TITLE
Investigate moving the arm via a script

### ISSUE THREAD

**Issue by DevanTurtle7** [talos-rit/operator#14]

**Comment by bl2060** [comment]
Using the following procedure, the operator can issue command to the Scorbot ER V to move it to a specific point via ACL

1. using 'defp \<pos\>' defines a position struct of name 'pos'
2. using 'here \<pos\>' loads the current position of the arm into the 'pos' structure
3. use shift commands to adjust the position:
  a. using 'shift \<pos\> by \<axis\> \<count\>' shifts the arm the specified number of encoder counter on the specified axis
  b. using 'shiftc \<pos\> by \<axis\> \<val\>' shifts the arm in the specified 'val' distance (either tenths of millimeters, or tenths of degrees) on the specified axis ('x', 'y', or 'z', as well as 'r' for wrist roll and 'p' for wrist pitch)
4. once the position structure has been modified sufficiently, 'move \<pos\> \<duration\>' will initiate the movement and attempt to complete it within the specified duration.
